#!/usr/bin/env node
// Validates the generated sitemap against the built HTML:
//  1. The sitemap lists exactly the indexable pages — none missing, and no
//     `noindex` page leaked in (Google reports those as "Submitted URL marked
//     noindex", which is a hard error in Search Console).
//  2. Every <url> carries a <lastmod> that is a valid W3C datetime and is not
//     in the future. A sitemap with no lastmod gives Google nothing to
//     prioritise on; one that lies gets its lastmod ignored site-wide.
//  3. Every <url> carries the same hreflang alternates the page itself
//     declares in its <head>. @astrojs/sitemap's built-in `i18n` option only
//     pairs URLs whose paths match after the locale prefix, so translated
//     slugs (/about/ ↔ /es/sobre/) silently lost their alternates — this
//     guards against that regression returning.
//
// Deliberately reads the alternates back out of the built HTML rather than
// importing PAGE_PAIRS: that way the sitemap is checked against what actually
// shipped, and the two can never drift apart silently.

import { readFile, readdir } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = join(ROOT, 'dist');

const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const RESET = '\x1b[0m';

const ROBOTS_NOINDEX_RE =
  /<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i;
const CANONICAL_RE =
  /<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i;
const CANONICAL_RE_FLIPPED =
  /<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i;

/** Earliest plausible lastmod — the repo's first commit is 2026-09-14. */
const MIN_LASTMOD = Date.parse('2026-01-01T00:00:00Z');

async function collectHtml(dir) {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await collectHtml(full)));
    else if (entry.isFile() && entry.name === 'index.html') out.push(full);
  }
  return out;
}

function extractAlternates(html) {
  const alt = new Map();
  const re =
    /<link[^>]+rel=["']alternate["'][^>]+hreflang=["']([^"']+)["'][^>]+href=["']([^"']+)["']/g;
  const flipped =
    /<link[^>]+href=["']([^"']+)["'][^>]+rel=["']alternate["'][^>]+hreflang=["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(html)) !== null) alt.set(m[1], m[2]);
  while ((m = flipped.exec(html)) !== null) alt.set(m[2], m[1]);
  return alt;
}

/**
 * Minimal sitemap reader. The files are machine-generated by
 * @astrojs/sitemap, so a full XML parser would be a dependency bought for
 * nothing — but we still fail loudly on anything we cannot read.
 */
function parseUrlset(xml) {
  const urls = [];
  const blocks = xml.match(/<url>[\s\S]*?<\/url>/g) ?? [];
  for (const block of blocks) {
    const loc = /<loc>([^<]+)<\/loc>/.exec(block)?.[1];
    if (!loc) continue;
    const lastmod = /<lastmod>([^<]+)<\/lastmod>/.exec(block)?.[1] ?? null;
    const links = new Map();
    const linkRe =
      /<xhtml:link[^>]+hreflang=["']([^"']+)["'][^>]+href=["']([^"']+)["']/g;
    let m;
    while ((m = linkRe.exec(block)) !== null) links.set(m[1], m[2]);
    urls.push({ loc, lastmod, links });
  }
  return urls;
}

async function readSitemapUrls(errors) {
  let indexXml;
  try {
    indexXml = await readFile(join(DIST, 'sitemap-index.xml'), 'utf8');
  } catch {
    errors.push('dist/sitemap-index.xml not found — run `npm run build` first.');
    return [];
  }

  const files = [...indexXml.matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1].split('/').pop())
    .filter(Boolean);

  if (files.length === 0) {
    errors.push('sitemap-index.xml references no sitemap files.');
    return [];
  }

  const urls = [];
  for (const name of files) {
    try {
      urls.push(...parseUrlset(await readFile(join(DIST, name), 'utf8')));
    } catch {
      errors.push(`sitemap-index.xml references ${name}, which does not exist.`);
    }
  }
  return urls;
}

async function main() {
  const errors = [];

  const htmlFiles = await collectHtml(DIST);
  if (htmlFiles.length === 0) {
    console.error(`${RED}FAIL${RESET} check-sitemap`);
    console.error('  - dist/ contains no HTML — run `npm run build` first.');
    process.exit(1);
  }

  // Build the expected picture from what actually shipped.
  const indexable = new Map(); // canonical URL → alternates Map
  const noindexCanonicals = new Set();

  for (const file of htmlFiles) {
    const html = await readFile(file, 'utf8');
    const rel = relative(DIST, file).replace(/\\/g, '/');
    const canonical =
      CANONICAL_RE.exec(html)?.[1] ?? CANONICAL_RE_FLIPPED.exec(html)?.[1];

    if (!canonical) {
      errors.push(`${rel}: no <link rel="canonical"> found`);
      continue;
    }
    if (ROBOTS_NOINDEX_RE.test(html)) {
      noindexCanonicals.add(canonical);
      continue;
    }
    indexable.set(canonical, extractAlternates(html));
  }

  const urls = await readSitemapUrls(errors);
  const seen = new Set();

  for (const { loc, lastmod, links } of urls) {
    if (seen.has(loc)) {
      errors.push(`${loc}: listed more than once in the sitemap`);
      continue;
    }
    seen.add(loc);

    if (noindexCanonicals.has(loc)) {
      errors.push(`${loc}: page is noindex but appears in the sitemap`);
      continue;
    }

    const expectedAlt = indexable.get(loc);
    if (!expectedAlt) {
      errors.push(`${loc}: in the sitemap but no built page has that canonical`);
      continue;
    }

    // 2. lastmod
    if (!lastmod) {
      errors.push(`${loc}: missing <lastmod>`);
    } else {
      const ts = Date.parse(lastmod);
      if (Number.isNaN(ts)) {
        errors.push(`${loc}: <lastmod> "${lastmod}" is not a valid W3C datetime`);
      } else if (ts > Date.now() + 60_000) {
        errors.push(`${loc}: <lastmod> "${lastmod}" is in the future`);
      } else if (ts < MIN_LASTMOD) {
        errors.push(
          `${loc}: <lastmod> "${lastmod}" predates the site — looks like a fallback, not a real date`,
        );
      }
    }

    // 3. alternates must mirror the page's own <head>
    for (const [hreflang, href] of expectedAlt) {
      const got = links.get(hreflang);
      if (!got) {
        errors.push(`${loc}: sitemap missing hreflang="${hreflang}" alternate`);
      } else if (got !== href) {
        errors.push(
          `${loc}: hreflang="${hreflang}" is ${got} in the sitemap but ${href} in the page`,
        );
      }
    }
    for (const hreflang of links.keys()) {
      if (!expectedAlt.has(hreflang)) {
        errors.push(
          `${loc}: sitemap declares hreflang="${hreflang}" that the page does not`,
        );
      }
    }
  }

  for (const canonical of indexable.keys()) {
    if (!seen.has(canonical)) {
      errors.push(`${canonical}: indexable page missing from the sitemap`);
    }
  }

  if (errors.length) {
    console.error(`${RED}FAIL${RESET} check-sitemap (${errors.length})`);
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }
  console.log(
    `${GREEN}OK${RESET} check-sitemap — ${seen.size} URLs, all with lastmod and matching alternates.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
